import Head from 'next/head'
import Sidebar from '@/components/Sidebar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Inqury app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.pinimg.com/236x/ab/4b/0e/ab4b0e078b96fd9701637c6a308fbfab.jpg" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/icofont.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/themify.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/flag-icon.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/feather-icon.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/scrollbar.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/animate.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/style.css" />
        <link id="color" rel="stylesheet" href="../assets/css/color-1.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="../assets/css/responsive.css" />
      </Head>
      <div className="container-fluid mb-5">
        <h1 className="text-center">Inquires</h1>
      </div>
      <div className='row p-3'>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card">
          <div className="project-box"><span className="badge badge-light-primary">Pending</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Nect Inquiry</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Intrested</span></div>
            <div className="col-6 font-primary">Yes</div>
            </div>
          </div>
        </div>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card ">
          <div className="project-box "><span className="badge badge-light-success">done</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Have Done Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Joining Date</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Course</span></div>
            <div className="col-6 font-primary">Python</div>
            </div>
          </div>
        </div>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card">
          <div className="project-box"><span className="badge badge-light-primary">Pending</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Nect Inquiry</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Intrested</span></div>
            <div className="col-6 font-primary">Yes</div>
            </div>
          </div>
        </div>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card">
          <div className="project-box"><span className="badge badge-light-primary">Pending</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Nect Inquiry</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Intrested</span></div>
            <div className="col-6 font-primary">Yes</div>
            </div>
          </div>
        </div>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card">
          <div className="project-box"><span className="badge badge-light-primary">Pending</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Nect Inquiry</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Intrested</span></div>
            <div className="col-6 font-primary">Yes</div>
            </div>
          </div>
        </div>
        <div className="col-xxl-4 col-lg-4 box-col-33 col-md-6 inquiry-card ">
          <div className="project-box "><span className="badge badge-light-success">done</span>
            <h4>Website Designing</h4>
            <div className="d-flex">
              <img className="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="image" />
              <div className="flex-grow-1 mb-0">
                <p className="fs-5mb-0">Tandel Nilkanth</p>
              </div>
            </div>
            <div className="flex-grow-1 mb-3">
              <p className="mb-0">Nikol , Ahmedabad </p>
            </div>
            <p>Have Done Inqiury For webdesigning course and programming languages</p>
            <div className="row details">
            <div className="col-6"><span>Inquiry date </span></div>
            <div className="col-6 font-primary">12/02/2023 </div>
            <div className="col-6"> <span>Joining Date</span></div>
            <div className="col-6 font-primary">19/02/2023</div>
            <div className="col-6"> <span>Course</span></div>
            <div className="col-6 font-primary">Python</div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}


Home.getLayout = function PageLayout(page) {
  return <>
    <Sidebar />
    {page}
  </>
}