import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Inqury app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      this is main content
    </div>
    </>
  )
}

Home.getLayout = function PageLayout(page) {
  return <>
  <Sidebar/>
  {page}
  </>
}